services:
  postgres:
    command: [postgres, -c, "shared_preload_libraries=pg_partman_bgw,pg_stat_statements", -c, pg_partman_bgw.dbname=scheduler, -c, pg_partman_bgw.role=scheduler, -c, pg_partman_bgw.interval=3600, -c, pg_stat_statements.track=all]
